[window]
decorations = "transparent"
opacity = 0.95
title = "Its me your Terminal"
option_as_alt = "Both"

padding.x = 12
padding.y = 30

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[keyboard]
# finally this is the fix for macos
bindings = [
  { key = "Left",  mods = "Alt",     chars = "\u001bB"   },
  { key = "Right", mods = "Alt",     chars = "\u001bF"   },
  { key = "Left",  mods = "Command", chars = "\u001bOH"  },
  { key = "Right", mods = "Command", chars =  "\u001bOF" },
  { key = "n", mods = "Alt", chars =  "~" },
  { key = "l", mods = "Alt", chars =  "@" },
]
